<a href="https://colab.research.google.com/github/srushtinalawade-gif/Study-of-NumPy/blob/main/Practical8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tools for EDA- Numpy
## Name: Srushti J. Nalawade
## PRN: 25070123157
## Batch: ENTC A1
## Experiment 8

In [ ]:
import numpy as np
a=np.array([10,20,30,40])
b=np.array([[1,2,3],[4,5,6]])

print(a)
print(b)

[10 20 30 40]
[[1 2 3]
 [4 5 6]]


In [ ]:
a.ndim

1

In [ ]:
b.ndim

2

In [ ]:

a.shape

(4,)

In [ ]:
b.shape

(2, 3)

In [ ]:
a.dtype

dtype('int64')

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
s=a+5
m=a*7
d=a/5
print(s)
print(m)
print(d)

[15 25 35 45]
[ 70 140 210 280]
[2. 4. 6. 8.]


In [ ]:
np.mean(a)

np.float64(25.0)

In [ ]:
np.median(a)

np.float64(25.0)

In [ ]:
np.sum(a)

np.int64(100)